package nadiendev.rusticrevived.world;

import java.util.Optional;

import nadiendev.rusticrevived.RusticRevived;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.block.grower.TreeGrower;
import net.minecraft.world.level.levelgen.feature.ConfiguredFeature;

/**
 * Tree growers for Rustic saplings. The configured features are generated by the world gen
 * datagen provider.
 */
public final class ModTreeGrowers {
	public static final ResourceKey<ConfiguredFeature<?, ?>> OLIVE_TREE = key("olive_tree");
	public static final ResourceKey<ConfiguredFeature<?, ?>> IRONWOOD_TREE = key("ironwood_tree");
	public static final ResourceKey<ConfiguredFeature<?, ?>> APPLE_TREE = key("apple_tree");

	public static final TreeGrower OLIVE = new TreeGrower(RusticRevived.NAMESPACE + ":olive", Optional.empty(), Optional.of(OLIVE_TREE), Optional.empty());
	public static final TreeGrower IRONWOOD = new TreeGrower(RusticRevived.NAMESPACE + ":ironwood", Optional.empty(), Optional.of(IRONWOOD_TREE), Optional.empty());
	public static final TreeGrower APPLE = new TreeGrower(RusticRevived.NAMESPACE + ":apple", Optional.empty(), Optional.of(APPLE_TREE), Optional.empty());

	private ModTreeGrowers() {
	}

	private static ResourceKey<ConfiguredFeature<?, ?>> key(String name) {
		return ResourceKey.create(Registries.CONFIGURED_FEATURE, RusticRevived.id(name));
	}
}
