# Gradle settings
org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

## Environment
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.240
neo_version_range=[21.1.0,)
loader_version_range=[4,)
java_version=21

# Parchment
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

## Mod metadata
mod_id=rustic
mod_namespace=rusticrevived
mod_name=Rustic Revived
mod_named=RusticRevived
mod_license=MIT
mod_version=1.0.0
mod_group_id=nadiendev.rusticrevived
tag_lanzador=NeoForge
build_number=0
mod_authors=NadienDev, cadaverous-eris, the-realest-stu
mod_description_short=
mod_description=NeoForge Port of Rustic. (A medieval themed mod based around decoration, exploration, agriculture, brewing and alchemy.)
issue_tracker=https://github.com/SrNadien/Rustic-Revived/issues

## Dependencies
jei_version=19.27.0.340
kubejs_version=2101.7.2-build.374
kubejs_version_range=[2101.7.0,)
rhino_version=2101.2.7-build.85
better_advanced_tooltips_version=2101.1.0-build.5
crafttweaker_version=21.0.39
quark_version=4.1-485-SNAPSHOT
zeta_version=1.1-40-SNAPSHOT
dynamictrees_version=G4uJ0UA0
