package nadiendev.rusticrevived.registry;

import nadiendev.rusticrevived.RusticRevived;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.block.entity.BannerPattern;

/**
 * Banner patterns (data driven since 1.20.5; generated by the world gen provider).
 */
public final class ModBanners {
	/** The Eris symbol, applied in a loom with the Eris banner pattern item. */
	public static final ResourceKey<BannerPattern> ERIS = ResourceKey.create(Registries.BANNER_PATTERN, RusticRevived.id("eris"));

	private ModBanners() {
	}
}
