package nadiendev.rusticrevived.compat.dynamictrees;

import nadiendev.rusticrevived.RusticRevived;
import nadiendev.rusticrevived.config.RusticConfig;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.Identifier;
import net.minecraft.server.packs.PackType;
import net.minecraft.server.packs.repository.Pack;
import net.minecraft.server.packs.repository.PackSource;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.fml.ModList;
import net.neoforged.neoforge.event.AddPackFindersEvent;

/**
 * Entry point of the optional Dynamic Trees integration. This class never touches Dynamic Trees
 * classes itself: everything that does lives in {@link DynamicTreesIntegration}, which is only
 * loaded when the mod is present.
 * <p>
 * The dynamic olive and ironwood trees themselves are data driven: the tree pack under
 * {@code trees/rusticrevived/} (families, species, leaves properties, JoCodes, biome populators)
 * plus their assets and loot tables are generated by
 * {@link nadiendev.rusticrevived.datagen.providers.RusticTreepackProvider}.
 */
public final class DynamicTreesCompat {
	public static final String MOD_ID = "dynamictrees";

	private DynamicTreesCompat() {
	}

	public static boolean isLoaded() {
		return ModList.get().isLoaded(MOD_ID);
	}

	/**
	 * Whether Dynamic Trees replaces Rustic's trees: static olive / ironwood world generation is
	 * disabled and apple seeds / saplings are planted as dynamic apple trees.
	 */
	public static boolean isActive() {
		if (!isLoaded()) {
			return false;
		}
		try {
			return RusticConfig.COMMON.enableDynamicTreesCompat.get();
		} catch (IllegalStateException notLoaded) {
			return RusticConfig.COMMON.enableDynamicTreesCompat.getDefault();
		}
	}

	/** Called during mod construction. */
	public static void init(IEventBus modBus) {
		if (isLoaded()) {
			DynamicTreesIntegration.init(modBus);
			modBus.addListener(DynamicTreesCompat::addPackFinders);
		}
	}

	/**
	 * Client assets of the Dynamic Trees blocks (branch models need the Dynamic Trees model loader)
	 * live in the built-in resource pack {@code resourcepacks/dynamictrees}, only enabled with the mod.
	 */
	private static void addPackFinders(AddPackFindersEvent event) {
		event.addPackFinders(Identifier.fromNamespaceAndPath(RusticRevived.MODID, "resourcepacks/dynamictrees"), PackType.CLIENT_RESOURCES,
				Component.literal("Rustic Revived: Dynamic Trees"), PackSource.BUILT_IN, true, Pack.Position.TOP);
	}
}
